# Autor:Valeria Ivonne Gutierrez Martinez
# Imagen de Python 
FROM python:3.8-slim

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia los archivos de la aplicación al contenedor
COPY . /app

# Instala las dependencias de Python
RUN pip install -r requirements.txt

# Puerto en el que se ejecutará la aplicación
EXPOSE 5000

# Comando para ejecutar la aplicación Flask
CMD ["python", "main.py"]
